
spring:
 application:
  name: peluqueria

 jackson:
  date-format: yyyy-MM-dd'T'HH:mm:ss
  time-zone: UTC

# datasource:
#  url: jdbc:h2:file:./data/store;AUTO_SERVER=TRUE
#  driverClassName: org.h2.Driver
#  username: sa
#  password:

 datasource:
  url: jdbc:mysql://localhost:3306/peluqueria?useSSL=false&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: admin

 h2:
  console:
   enabled: true

# jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#  defer-datasource-initialization: true
#  hibernate:
#   ddl-auto: create-drop

 jpa:
  hibernate:
   ddl-auto: create-drop
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect
  defer-datasource-initialization: true

 sql:
  init:
   mode: always


server:
 port: 8081

security:
 jwt:
  secret-key: c5cce0a3980ae936bbb7ec9c526f4057043c28b0da0bbb5caca7b713ad2de9df
  expiration-time: 3600000

springdoc:
 swagger-ui:
  enabled: true
 api-docs:
  enabled: true


